name = "peerdrop"
main = "workers-site/index.js"
compatibility_date = "2023-04-23"

# Replace with your actual Cloudflare account ID
account_id = "your-account-id"

[site]
bucket = "./src"

[build]
command = "npm run build"

# Durable Objects configuration
[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["RoomDurableObject"]

[env.production]
name = "peerdrop"
route = "peerdrop.pages.dev/*" # Replace with your custom domain if you have one
zone_id = "your-zone-id" # Replace with your zone ID if using a custom domain
